### PR TITLE
Allow using ActiveModel::Validation errors

### PR DESCRIPTION
**Pull request by bguban**
Now if you use `simple_command` in Rails you can include `ActiveModel::Validations` into class and use it's `errors` functionality which is match wider.

PS Could you release a new ruby gem? Because the current one is 4 years old.

### CODE REVIEW

**Comment by kennyadsl** [comment]
Hey there, I'm ok with this change but can you please remove the version change from this PR? It will be handled separately. Thanks!

**Comment by bguban** [comment]
> Hey there, I'm ok with this change but can you please remove the version change from this PR? It will be handled separately. Thanks!

@kennyadsl,  Done. Would you like me to add some documentation for this functionality?

**Comment by kennyadsl** [comment]
Yes, it would be great. Thanks!

**Comment by bguban** [comment]
Hi @kennyadsl, I updated the documentation a little. Could you take a look?

**Comment by kennyadsl** [comment]
Thank you!

**Pull request merged**
